spring:
  application.name: iot-sensor-collector
  threads.virtual.enabled: true
  cassandra:
    request:
      consistency: quorum
      timeout: 1s
    contact-points: s-cnode-1:9042
    local-datacenter: datacenter1
  flyway.enabled: false

management:
  tracing:
    sampling:
      probability: 1
  otlp:
    tracing:
      endpoint: http://tracer:4318/v1/traces
      transport: http

custom:
  flyway:
    schemas: flyway_keyspace
    sql-migration-suffixes: .cql
    locations: classpath:db/migration

logging:
  structured.format:
    console: logstash
    file: logstash
  logback:
    rollingpolicy:
      max-file-size: 1MB
      total-size-cap: 5MB
      file-name-pattern: ${LOG_FILE}.%d{yyyy-MM-dd}.%i
  file:
    name: ./app-logs/iot-sensor-app.log