FROM ubuntu:24.04
RUN apt-get update && apt-get install -y wget gpg unzip

# corretto
RUN wget -O - https://apt.corretto.aws/corretto.key | gpg --dearmor -o /usr/share/keyrings/corretto-keyring.gpg && \
  echo "deb [signed-by=/usr/share/keyrings/corretto-keyring.gpg] https://apt.corretto.aws stable main" | tee /etc/apt/sources.list.d/corretto.list
RUN apt-get update; apt-get install -y java-25-amazon-corretto-jdk

ENTRYPOINT ["/bin/sh", "-c", "sleep 99999999d"]
