name: app

services:
  dev:
    networks:
      - app_net
    build:
      context: ../
      dockerfile: app/Dockerfile-dev
    ports:
      - "8080:8080"
      - "5005:5005"
    user: 1000:1000
    working_dir: "/app"
    volumes:
      - "../:/app"

networks:
  app_net:
    external: true