service:
  extensions: [jaeger_storage, jaeger_query, healthcheckv2, zpages]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [jaeger_storage_exporter]
  telemetry:
    resource:
      service.name: jaeger
    metrics:
      level: detailed
      readers:
        - pull:
            exporter:
              prometheus:
                host: "${env:JAEGER_LISTEN_HOST:-0.0.0.0}"
                port: 8888
    logs:
      level: info

receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:

exporters:
  jaeger_storage_exporter:
    trace_storage: simple_storage

extensions:
  jaeger_storage:
    backends:
      simple_storage:
        memory:
          max_traces: 100000
  jaeger_query:
    storage:
      traces: simple_storage
  healthcheckv2:
    use_v2: true
    http:
      endpoint: "${env:JAEGER_LISTEN_HOST:-0.0.0.0}:13133"
  zpages:
    endpoint: "${env:JAEGER_LISTEN_HOST:-0.0.0.0}:27778"